// Generated by Haxe 3.4.0
(function () { "use strict";
var ApplicationEntry = function() {
	console.log("ApplicationEntry:Constructor");
	var j = new com_jungle_Jungle();
	console.log(j.isKingAvailable());
	console.log(j.getAllTrees());
};
ApplicationEntry.main = function() {
	console.log("main");
	var ApplicationEntry1 = new ApplicationEntry();
};
var com_jungle_Animal = function(type,age) {
	if(age == null) {
		age = 0.0;
	}
	console.log("Animal:Constructor");
	this.type = type;
	this.age = age;
};
com_jungle_Animal.prototype = {
	getType: function() {
		return this.type;
	}
	,getAge: function() {
		return this.age;
	}
};
var com_jungle_Jungle = function() {
	console.log("Jungle:Constructor");
	this.allAnimals = [];
	this.allTrees = [];
	this.isKingAdded = false;
	var _g = 0;
	while(_g < 10) {
		var i = _g++;
		var t = new com_jungle_Tree(i);
		this.allTrees.push(t);
	}
	this.addKing();
};
com_jungle_Jungle.prototype = {
	addKing: function() {
		var king = new com_jungle_Animal("Lion",1.0);
		this.allAnimals.push(king);
		this.isKingAdded = true;
	}
	,isKingAvailable: function() {
		return this.isKingAdded;
	}
	,getAllTrees: function() {
		return this.allTrees;
	}
};
var com_jungle_Tree = function(age,name) {
	if(name == null) {
		name = "unknown Tree";
	}
	if(age == null) {
		age = 0.0;
	}
	console.log("Tree : Constructor");
	this.age = age;
	this.name = name;
};
com_jungle_Tree.prototype = {
	breath: function() {
		console.log("Tree:breath");
	}
	,getName: function() {
		return this.name;
	}
	,getAge: function() {
		return this.age;
	}
};
ApplicationEntry.main();
})();
